version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cute_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_bot_data
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
